import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";



const poppins = localFont({
  src: "./fonts/Poppins-Black.ttf",
  variable: "--font-poppins",
  weight: "900",
  display: "swap", // Added display property for better font loading
});


export const metadata: Metadata = {
  title: "Hyperhire assignment",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/hyperhire_hq_logo.jpeg" />
      </head>
      <body
        className={`${poppins.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
